### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by zhangjunior** [yihui-he/Xception-caffe#3]
How much memory did you used?
I try this model with GTX1080 which is 8G graphic memory, but it's  "out of memory"...

**Comment by ethanhe42** [comment]
@zhangjunior about 11G

**Comment by zhangjunior** [comment]
Thanks!



发自我的小米手机
在 Yihui He 何宜晖 <notifications@github.com>，2017年4月10日 20:06写道：

@zhangjunior<https://github.com/zhangjunior> about 11G
